### ISSUE TITLE
Doesn't work with Yarn

### ISSUE THREAD

**Issue by Samuel-Martineau** [terminal-junkies/npmx#5]
When installed with Yarn, running `npmx` gives the following error:
```
Error: Cannot find module 'utils/getTheme'
Require stack:
- /Users/samuel_martineau/.config/yarn/global/node_modules/@terminal-junkies/npmx/src/pages/home/widgets/taskList.js
- /Users/samuel_martineau/.config/yarn/global/node_modules/@terminal-junkies/npmx/src/pages/home/index.js
- /Users/samuel_martineau/.config/yarn/global/node_modules/@terminal-junkies/npmx/src/index.js
- /Users/samuel_martineau/.config/yarn/global/node_modules/@terminal-junkies/npmx/bin/npmx.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1065:15)
    at Function.Module._resolveFilename (/Users/samuel_martineau/.config/yarn/global/node_modules/module-alias/index.js:49:29)
    at Function.Module._load (internal/modules/cjs/loader.js:911:27)
    at Module.require (internal/modules/cjs/loader.js:1125:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/Users/samuel_martineau/.config/yarn/global/node_modules/@terminal-junkies/npmx/src/pages/home/widgets/taskList.js:4:18)
    at Module._compile (internal/modules/cjs/loader.js:1236:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1257:10)
    at Module.load (internal/modules/cjs/loader.js:1085:32)
    at Function.Module._load (internal/modules/cjs/loader.js:950:14)
    at Module.require (internal/modules/cjs/loader.js:1125:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at module.exports (/Users/samuel_martineau/.config/yarn/global/node_modules/@terminal-junkies/npmx/src/pages/home/index.js:4:20)
    at module.exports (/Users/samuel_martineau/.config/yarn/global/node_modules/@terminal-junkies/npmx/src/index.js:126:20)
    at Object.<anonymous> (/Users/samuel_martineau/.config/yarn/global/node_modules/@terminal-junkies/npmx/bin/npmx.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:1236:30)
```

Is there any plans to make this tool compatible with Yarn? Because it looks really cool...

**Comment by rajasegar-c** [comment]
Is it something related to module-alias, I am not sure let me check, and I want to build a separate one for yarn because the command syntax and semantics vary from npm a little, and I don't want to put a lot of if else code, glad someone wants for yarn

**Comment by Samuel-Martineau** [comment]
Should I close the issue? Or would you prefer if I kept it opened?

**Comment by rajasegar** [comment]
No, let it be, let me find the root cause, I will close once it is done.
BTW, You installed it using
```
yarn global add @terminal-junkies/npmx
```
right?

**Comment by Samuel-Martineau** [comment]
I did install it with that command

**Comment by rajasegar** [comment]
@Samuel-Martineau Your wish came true for yarn
https://github.com/terminal-junkies/yarnx

**Comment by Samuel-Martineau** [comment]
Thanks! Maybe you should update the README: it says to install yarnx with npm...

**Comment by rajasegar** [comment]
@Samuel-Martineau  Done
